{
 "title": "Event Viewer - Threat Hunting",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "Database",
    "query": "SELECT name FROM system.databases where name like 'eventlog%';\n"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "SELECT name FROM system.tables WHERE database IN (${database})"
   },
   {
    "name": "Computer",
    "label": "Computer",
    "query": "SELECT DISTINCT(log.Computer) AS Computer from eventlogs.jsonlogs;"
   }
  ]
 },
 "panels": [
  {
   "title": "Event Viewer - Threat Hunting Example using Fluent Bit and ClickHouse Cloud",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Event Viewer - Sysmon Threat Hunting Example using Fluent Bit and ClickHouse Cloud\n\nThis is an example dashboard created with Windows Event Viewer data received using Fluent Bit and stored in ClickHouse Cloud. Additionally\nit's using [Sysmon](https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon) to generate rich event that help to identify malicious or anomalous activity and understand how intruders and malware operate on your network.\nData source is connected using the [ClickHouse plugin for Grafana](https://grafana.com/grafana/plugins/grafana-clickhouse-datasource/)\n\nFor more information or syntax help see: [ClickHouse.com](https://clickhouse.com/docs/en/sql-reference/) and [fluentbit.io](https://docs.fluentbit.io/manual)"
   }
  },
  {
   "title": "Events received over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time,  count(log) total FROM eventlogs.jsonlogs group by time;"
    }
   ]
  },
  {
   "title": "Total log lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  sum(total_rows) as \"Total rows\" FROM system.tables WHERE database IN (${database}) AND name IN (${table})"
    }
   ]
  },
  {
   "title": "Audit Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(log.EventID) FROM ${database:raw}.${table:raw} WHERE log.Keywords == '0x8020000000000000'"
    }
   ]
  },
  {
   "title": "Audit Failure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(log.EventID) FROM ${database:raw}.${table:raw} WHERE log.Keywords == '0x8010000000000000';\n"
    }
   ]
  },
  {
   "title": "Percentage Audit Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select round(a.percentage) from (SELECT  count(log.EventID) as audit_all,(SELECT count(log.EventID) FROM eventlogs.jsonlogs WHERE log.Keywords == '0x8010000000000000') as audit_failed, audit_failed/(audit_all/100) as percentage FROM eventlogs.jsonlogs) as a;"
    }
   ]
  },
  {
   "title": "Process creation",
   "type": "stat",
   "description": "The process creation event provides extended information about a newly created process. The full command line provides context on the process execution. The ProcessGUID field is a unique value for this process across a domain to make event correlation easier. The hash is a full hash of the file with the algorithms in the HashType field.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '1' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "Process changed",
   "type": "stat",
   "description": "The change file creation time event is registered when a file creation time is explicitly modified by a process. This event helps tracking the real creation time of a file. Attackers may change the file creation time of a backdoor to make it look like it was installed with the operating system. Note that many processes legitimately change the creation time of a file; it does not necessarily indicate malicious activity.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '2' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "Network connection",
   "type": "stat",
   "description": "The network connection event logs TCP/UDP connections on the machine. It is disabled by default. Each connection is linked to a process through the ProcessId and ProcessGuid fields. The event also contains the source and destination host names IP addresses, port numbers and IPv6 status.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '3' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "Sysmon service state changed",
   "type": "stat",
   "description": "The service state change event reports the state of the Sysmon service (started or stopped).",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '4' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "Process terminated",
   "type": "stat",
   "description": "The process terminate event reports when a process terminates. It provides the UtcTime, ProcessGuid and ProcessId of the process.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '5' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "Driver loaded",
   "type": "stat",
   "description": "The driver loaded events provides information about a driver being loaded on the system. The configured hashes are provided as well as signature information. The signature is created asynchronously for performance reasons and indicates if the file was removed after loading.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '6' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "Image loaded",
   "type": "stat",
   "description": "The image loaded event logs when a module is loaded in a specific process. This event is disabled by default and needs to be configured with the \"–l\" option. It indicates the process in which the module is loaded, hashes and signature information. The signature is created asynchronously for performance reasons and indicates if the file was removed after loading. This event should be configured carefully, as monitoring all image load events will generate a significant amount of logging.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '7' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "CreateRemoteThread",
   "type": "stat",
   "description": "The CreateRemoteThread event detects when a process creates a thread in another process. This technique is used by malware to inject code and hide in other processes. The event indicates the source and target process. It gives information on the code that will be run in the new thread: StartAddress, StartModule and StartFunction. Note that StartModule and StartFunction fields are inferred, they might be empty if the starting address is outside loaded modules or known exported functions.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '8' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "RawAccessRead",
   "type": "stat",
   "description": "The RawAccessRead event detects when a process conducts reading operations from the drive using the \\\\.\\ denotation. This technique is often used by malware for data exfiltration of files that are locked for reading, as well as to avoid file access auditing tools. The event indicates the source process and target device.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '9' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "ProcessAccess",
   "type": "stat",
   "description": "The process accessed event reports when a process opens another process, an operation that’s often followed by information queries or reading and writing the address space of the target process. This enables detection of hacking tools that read the memory contents of processes like Local Security Authority (Lsass.exe) in order to steal credentials for use in Pass-the-Hash attacks. Enabling it can generate significant amounts of logging if there are diagnostic utilities active that repeatedly open processes to query their state, so it generally should only be done so with filters that remove expected accesses.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '10' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "FileCreate",
   "type": "stat",
   "description": "File create operations are logged when a file is created or overwritten. This event is useful for monitoring autostart locations, like the Startup folder, as well as temporary and download directories, which are common places malware drops during initial infection.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '11' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "RegistryEvent (ObjCreate/Delete)",
   "type": "stat",
   "description": "Registry key and value create and delete operations map to this event type, which can be useful for monitoring for changes to Registry autostart locations, or specific malware registry modifications.\n\nSysmon uses abbreviated versions of Registry root key names, with the following mappings:\n\nKey name\t                        Abbreviation\nHKEY_LOCAL_MACHINE\tHKLM\nHKEY_USERS\t               HKU\nHKEY_LOCAL_MACHINE\\System\\ControlSet00x\tHKLM\\System\\CurrentControlSet\nHKEY_LOCAL_MACHINE\\Classes\tHKCR",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '12' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "RegistryEvent (ValueSet)",
   "type": "stat",
   "description": "This Registry event type identifies Registry value modifications. The event records the value written for Registry values of type DWORD and QWORD.\n\nSysmon uses abbreviated versions of Registry root key names, with the following mappings:\n\nKey name\t                        Abbreviation\nHKEY_LOCAL_MACHINE\tHKLM\nHKEY_USERS\t               HKU\nHKEY_LOCAL_MACHINE\\System\\ControlSet00x\tHKLM\\System\\CurrentControlSet\nHKEY_LOCAL_MACHINE\\Classes\tHKCR",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '13' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "RegistryEvent (K/V Rename)",
   "type": "stat",
   "description": "Registry key and value rename operations map to this event type, recording the new name of the key or value that was renamed.\nSysmon uses abbreviated versions of Registry root key names, with the following mappings:\n\nKey name\t                        Abbreviation\nHKEY_LOCAL_MACHINE\tHKLM\nHKEY_USERS\t               HKU\nHKEY_LOCAL_MACHINE\\System\\ControlSet00x\tHKLM\\System\\CurrentControlSet\nHKEY_LOCAL_MACHINE\\Classes\tHKCR",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '14' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "FileCreateStreamHash",
   "type": "stat",
   "description": "This event logs when a named file stream is created, and it generates events that log the hash of the contents of the file to which the stream is assigned (the unnamed stream), as well as the contents of the named stream. There are malware variants that drop their executables or configuration settings via browser downloads, and this event is aimed at capturing that based on the browser attaching a Zone.Identifier \"mark of the web\" stream.\n\nKey name\t                        Abbreviation\nHKEY_LOCAL_MACHINE\tHKLM\nHKEY_USERS\t               HKU\nHKEY_LOCAL_MACHINE\\System\\ControlSet00x\tHKLM\\System\\CurrentControlSet\nHKEY_LOCAL_MACHINE\\Classes\tHKCR",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '15' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "ServiceConfigurationChange",
   "type": "stat",
   "description": "This event logs changes in the Sysmon configuration - for example when the filtering rules are updated.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '16' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "PipeCreated",
   "type": "stat",
   "description": "This event generates when a named pipe is created. Malware often uses named pipes for interprocess communication.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '17' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "PipeConnected",
   "type": "stat",
   "description": "This event logs when a named pipe connection is made between a client and a server.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '18' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "WMI Eventfilter Activity Detected",
   "type": "stat",
   "description": "When a WMI event filter is registered, which is a method used by malware to execute, this event logs the WMI namespace, filter name and filter expression.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '19' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "WMI EventConsumer  Activity Detected",
   "type": "stat",
   "description": "This event logs the registration of WMI consumers, recording the consumer name, log, and destination.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '20' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "WMI EventConsumerToFilter  Activity Detected",
   "type": "stat",
   "description": "When a consumer binds to a filter, this event logs the consumer name and filter path.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '21' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "DNSEvent (Total DNS queries)",
   "type": "stat",
   "description": "DNSEvent (DNS queries executed). This event is generated when a process executes a DNS query, whether the result is successful or fails, cached or not. The telemetry for this event was added for Windows 8.1 so it is not available on Windows 7 and earlier.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '22' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "FileDelete(File Delete archived)",
   "type": "stat",
   "description": "A file was deleted. Additionally to logging the event, the deleted file is also saved in the ArchiveDirectory (which is C:\\Sysmon by default). Under normal operating conditions this directory might grow to an unreasonable size - see event ID 26: FileDeleteDetected for similar behavior but without saving the deleted files.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '23' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "ClipboardChange(NewContent)",
   "type": "stat",
   "description": "This event is generated when the system clipboard contents change.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '24' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "ProcessTampering",
   "type": "stat",
   "description": "Process image change. This event is generated when process hiding techniques such as \"hollow\" or \"herpaderp\" are being detected.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '25' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "FileDeleteDetected",
   "type": "stat",
   "description": "File Delete logged aka a file was deleted.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '26' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "FileBlockExecutable",
   "type": "stat",
   "description": "This event is generated when Sysmon detects and blocks the creation of executable files.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '27' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "FileBlockShredding",
   "type": "stat",
   "description": "This event is generated when Sysmon detects and blocks file shredding from tools such as [SDelete](https://learn.microsoft.com/en-us/sysinternals/downloads/sdelete)",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '28' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "Internal Error",
   "type": "stat",
   "description": "This event is generated when an error occurred within Sysmon. They can happen if the system is under heavy load and certain tasks could not be performed or a bug exists in the Sysmon service, or even if certain security and integrity conditions are not met. You can report any bugs on the Sysinternals forum or over Twitter (@markrussinovich).",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT(log.EventID) FROM  eventlogs.jsonlogs where log.EventID == '255' AND log.Channel == 'Microsoft-Windows-Sysmon/Operational'"
    }
   ]
  },
  {
   "title": "Top 10 - EventIDs on Channel Received",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT log.Channel as Channel, log.EventID as EventID, count(log.EventID) as \"Total Events Received\" FROM eventlogs.jsonlogs group by log.Channel, log.EventID order by \"Total Events Received\" DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Last (10) occurred Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT max(timestamp) as \"Since\", log.Channel as Channel, log.Message as \"Latest Message\" FROM eventlogs.jsonlogs group by log.Message, log.Channel order by \"Since\" DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Log Event Stream filtered per Computer",
   "type": "logs",
   "description": "Use 'All' or filter per Computername using selector above.",
   "gridPos": { "h": 28, "w": 12, "x": 0, "y": 31 },
   "repeat": "Computer",
   "targets": [
    {
     "rawSql": "SELECT\n          timestamp AS log_time,\n          log.Message AS Message,\n          log.Channel AS Channel,\n          log.Computer AS Computer,\n          log.EventID AS EventID,\n          log.ActivityID AS ActivityID,\n          log.EventRecordID AS EventRecordID,\n          log.Keywords AS Keywords,\n          log.Level AS SeverityLevel,\n          log.Opcode AS OPcode,\n          log.ProcessID AS ProcessID,\n          log.ProviderGuid AS ProviderGuid,\n          log.ProviderName AS ProviderName,\n          log.Qualifiers AS Qualifiers,\n          log.RelatedActivityID AS RelatedActivityID,\n          log.StringInserts AS StringInserts,\n          log.Task AS Task,\n          log.ThreadID AS ThreadID,\n          log.TimeCreated AS TimeCreated,\n          log.UserID AS UserID,\n          log.Version AS Version\nFROM eventlogs.jsonlogs ORDER BY timestamp DESC LIMIT 1000"
    }
   ]
  }
 ]
}